# Generated by Django 5.0.6 on 2024-06-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to='media/new_images'),
            preserve_default=False,
        ),
    ]
